### ISSUE TITLE
Intermediate snapshots generation

### ISSUE THREAD

**Issue by adlzanchetta** [Iowa-Flood-Center/asynch#12]
Give a option in the global file so that the user can specify an interval of inner snapshots to be generated. 
The user has to specify the time interval, in seconds, for the snapshots to be generated (e.g. 1 hour =3600). 
Also, make the name of generated snapshots flexible for the multiple snapshots generation.

Suggestions:
- have one more option for saving outputs:
   (e.g.  "%Snapshot information (0 = none, 1 = .rec, 2 = .dbc, 3 = .h5, 4 = sequential .h5"  )
- argument for option 4 having a delta_timestamp and a TIMESTAMP keyword to be replaced by ending timestamp
   (e.g. "4 /Groups/IFC/back_time/1475856712/snapshot_mdlX_TIMESTAMP.h5 3600")

**Comment by sdebionne** [comment]
I have switched the order of the param, the interval of the snapshots being first to be more constant with other settings and is expressed in the run time unit, that is minute most of the time. Would that work for you?

%Snapshot information (0 = none, 1 = .rec, 2 = .dbc, 3 = .h5, 4 = sequential .h5
4 60 /Groups/IFC/back_time/1475856712/snapshot_mdlX_TIMESTAMP.h5

There is an issue with the timestamp: there is no way with the current implementation to have an absolute timestamp (e.g. unix time) because the solver does not "know" about the time, it only knows about the time from the beginning of the simulation. Shall we fix that to?

**Comment by sdebionne** [comment]
Added in v1.1.0, enhanced in v1.2.0
